site_name: Docs
theme:
  name: material
  palette:
    primary: red
    accent: red
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
